/* ============================================================================
   MEZUN İSİM LİSTELERİ — "Mezunlarımızın Takdimi" ekranı için.
   Kaynak: Mezuniyet 2026 son.docx (otomatik çıkarıldı). Sıra = geçit/ACTIVE_PROGRAMS sırası.
   Anahtar: program slug'ı (lib/data.js ile birebir).
============================================================================ */
export const GRADUATES = {
  "insaat-teknolojisi": [ // 82
    "HALİS EMİR TURAN",
    "DERİN ASLI BAYGUT",
    "TUĞBA VELİOĞULLARI",
    "YUNUS EMRE ESEN",
    "BERFİN TAŞTAN",
    "HAZAR TÜRK ALTUNTAŞ",
    "SEDAT ALP",
    "MERVENUR KARANFİL",
    "NEHİR METLİ",
    "ABDURRAHMAN ALTAY",
    "BUSE SÖZER",
    "ERDAL TEKİN",
    "ULAŞ ALKAN",
    "HANDAN ÜRGER",
    "EGE GÜNGÖR",
    "MEHMET SARITOP",
    "ADEM YİĞİT ÇATAK",
    "GAMZE YALVAÇ",
    "YASİN SARICA",
    "MEHMET VATAN",
    "BORAN ÇİFTÇİ",
    "FURKAN TALHA KARAKUŞ",
    "ONUR ELALDI",
    "ROHAT GÜNGÖRMÜŞ",
    "YAĞIZ MELİK ASLAN",
    "SEDAT YATİCİ",
    "ÖMER FARUK ARAZ",
    "FURKAN EMRE TURAN",
    "FURKAN ŞAVLİ",
    "MEHMET DENİZ MARANGOZ",
    "SELEN KAHRAMAN",
    "MEHMET CAN ÜNAL",
    "TANER ATMACA",
    "GÖRKEM ÖZDEMİR",
    "EGEMEN GÜLENÇ",
    "ATALAY ENGİN",
    "CEREN ALTIN",
    "EFE ARDA ÖZTOKUÇ",
    "ROJVAN ERDUNDAR",
    "MUHARREM SERBEST",
    "YİĞİT KEREM AYDIN",
    "MELİKE AKKAYA",
    "MURAT SÖYLEMEZ",
    "YASİN ÇETİN",
    "KEREM ÖZKAN",
    "TEKİN ERTEKİN",
    "AZRA KELEŞ",
    "İBRAHİM MELİK ALTINTAŞ",
    "MEHMET AGİT ÇAKMAK",
    "SEYMEN KUL",
    "MAHİR POYRAZ TOPSAKAL",
    "BURCU HOŞER",
    "AZAD YARIŞ",
    "NİLSU DİLA ÇANKAYA",
    "ÖMÜRCAN GÖKMEN",
    "MUHAMMED EREN DOĞRU",
    "BERKAY SARIDEDE",
    "İSMAİL ERGÜL",
    "ERENCEM BABACANOĞLU",
    "MERT ÖZ",
    "ATAKAN KAYA",
    "GURBET GÖKER",
    "ÇAĞATAY ÇALIŞKAN",
    "HAKAN KAYA",
    "MURAT DOĞAN",
    "EFE MERT TEKELİ",
    "RECEP ANIL GÖKDENİZ",
    "ATABERK ARIKAN",
    "DOĞUKAN YUMLU",
    "ÖZGÜR TERLEMEZ",
    "MUSTAFA YALÇIN",
    "MUHAMMED BUĞRA KURT",
    "ENES DOĞRU",
    "SERAP TAVACI",
    "YAVUZ SELİM GÜNAL",
    "EMRE BÖYÜKAYDIN",
    "GÜLÇİN ÖZKAN",
    "HÜSEYİN MENDER",
    "AKIN ALP HEKİM",
    "HALİME TURAY",
    "BURAK KURT",
    "ZEHRA ARSLAN",
  ],
  "buyuk-veri-analistligi": [ // 30
    "FATİH KOCATAHTACI",
    "GÖRKEM TAHA ÇANAKCI",
    "MUHAMMET DOĞAN KURU",
    "ALİ TALHA BAYRAM",
    "AYDAN ALOĞLU",
    "AYŞEGÜL ÖZZEYBEK",
    "ŞEYMA GÜRLEYEN AKKAYA",
    "HAKKI YİĞİT YILDIZ",
    "AHMET TUNAHAN GÖKTAŞ",
    "MEHMET AKİF ALBAYRAK",
    "İBRAHİM EMİN VARLI",
    "SELİNAY NARİN",
    "ALPEREN KÖYBAŞI",
    "ASRIN ŞAHİN",
    "YAREN ARKUN",
    "SERCAN ARTUÇ",
    "ŞEVİN DEMİRCAN",
    "ALPER ASLANER",
    "HATİCE SOĞANCI",
    "ALİ GÜNDOĞDU",
    "EREN ATA",
    "BÜŞRA GÜR",
    "DİLARA DEMİRBAŞ",
    "MELİKE SİRMEN",
    "FEYZA DÖNMEZ",
    "AYLİN KONAR",
    "AYLİN KONAR",
    "TANER ŞAHİN",
    "ABDÜLSAMET ARTUN",
    "BORA AKBULUT",
  ],
  "makine": [ // 74
    "BERKAY TEKDAL",
    "HASAN EMRE KUTUR",
    "İSMAİL HAKKI GÜVEN",
    "GONCA TUR",
    "YALIN YÜREKLİ",
    "MUSTAFA ARDA BALABAN",
    "ABDULREZZAK UĞURLU",
    "YAĞMUR TÜRKYILMAZ",
    "MERYEM EVİS",
    "MURAT CAN DEMİR",
    "SERHAT YAĞCI",
    "LEVENT BİNGÜL",
    "KAAN ACARKANLI",
    "ALİ OSMAN AYDIN",
    "ARDA AKYOL",
    "MUSTAFA TETİK",
    "ENES ORADA",
    "SEBAHATTİN GÜMÜŞ",
    "FATİH SELİM AKBIYIK",
    "ALİ ZENGİN",
    "NİYAZİ ERDEM TEKİN",
    "FURKAN ÇELİK",
    "GÖRKEM DEVRİM",
    "MEHMET EGE KARABIYIK",
    "MEHMET ÖZCAN",
    "ORKUN TEKE",
    "NAFİZ ALİ KARABUNAR",
    "ATAKAN TAHSİN ÖZTÜRK",
    "ASİL ŞAHBAZ",
    "MUSTAFA KADİR HASAR",
    "ALİ GÜLTEKİN",
    "ŞÜKRÜ SAVCI",
    "MEHMET FATİH KAYA",
    "BATUHAN ENGİN",
    "HİMMET AKDAĞ",
    "AHMETCAN ULU",
    "MURAT KAVÇIN",
    "EMİR BARTIK",
    "ANIL KADİR ALTOĞ",
    "SÜLEYMAN ORUS",
    "ZEYNEL ABİDİN AKKUŞ",
    "GÖKAY SARIBEK",
    "MESUT DÖNMEZ",
    "ERDEM ALP CAN",
    "EFEBERK YAVUZER",
    "BATUHAN OCAK",
    "FAHRETTİN ESAT SONGUR",
    "ZÜBEYR TALHA SAVRAN",
    "ATAKAN BOZTEPE",
    "ŞAHİN AKABE NURGÖZ",
    "MELİH YAŞAR ER",
    "İBRAHİM UMUT MERMER",
    "UMUT TÜRKAN",
    "AHMET TUNCA",
    "EMİRHAN KARAKAYA",
    "YUNUS ÖZÇELİK",
    "YUSUF TALHA BULUT",
    "İSMAİL MURŞİL",
    "YAĞIZ SEVERGÜN",
    "HASAN ARSLAN",
    "YAMAN RIZA ÖZSOYBAŞ",
    "FURKAN TANER",
    "EFECAN HEPKARAAĞAÇ",
    "ÇAĞRI İNCE",
    "MEHMET ÖZKAN",
    "MUSTAFA EFE EKMEKÇİ",
    "FATMA AFŞAR",
    "GÖKTUĞ EĞİN",
    "ARZU ÖZBAŞLI",
    "YUSUF EZGİN",
    "MELİSA DOĞA ÇOBAN",
    "ALİ BERKE GÜNEŞ",
    "EMİRHAN AYBAR",
    "HALİL İNCİL",
  ],
  "makine-resim-ve-konstruksiyon": [ // 53
    "RUHAT AYKAL",
    "BERKE GÜMÜŞ",
    "SAMED GEDİK",
    "MERYEM BEYZA İLHAN",
    "İLKER ÖZTANRIKULU",
    "ZEYNEP KARAKAYA",
    "MEHMET KORKMAZ",
    "DİLARA BARLAK",
    "SABRİ BORA MÜLAZIMOĞLU",
    "YUSUFCAN BULUT",
    "ÜMRE BERAY KÖMÜRCÜOĞLU",
    "ATAKAN BERBEROĞLU",
    "EREN GENÇ",
    "EMİRHAN EROL",
    "ATAKAN GÖÇ",
    "SUDENUR COŞKUN",
    "CEYLİN ÖZTÜRK",
    "BARIŞ AYDIN",
    "MEHMET ÖZKAN",
    "FURKAN YILMAZ",
    "İSMAİL MERT BÖÇÜK",
    "TARIK AKAR",
    "METİN KARATAŞTAN",
    "OSMAN EGEMEN ERKİ",
    "EMİRHAN AYMALI",
    "YALÇIN YAĞIZ PELİNDAĞ",
    "BUĞRA GÜREL",
    "ÇAĞLAR GEDİK",
    "NAZIM BEKİR GÖZTAK",
    "KUBİLAY AŞKIN TURAN",
    "BUĞRA SEYMAN",
    "ŞEYMANUR AÇIKGÖZ",
    "MUHAMMED NECDET GÖKEZ",
    "BORA ARI",
    "İLAYDA EKEN",
    "EMİRHAN ORUÇ DEMİR",
    "CEYLİN KÖKTUT",
    "CİHAD YILMAZ",
    "BERKAY AKPINAR",
    "HAYRİ BAŞAR BOZKURT",
    "EMRE ÇAM",
    "MEHMET ARSLAN",
    "ERDİ GÜL",
    "CANER YÖRENÇ",
    "EMİNENAZ ELDİVEN",
    "UĞUR TEZCAN",
    "HASAN KARAKAŞ",
    "ZEYNEP YAĞMUR DEMİRTAŞ",
    "RAŞİT SEZER ŞENLİK",
    "UĞUR KUZGUN",
    "HİLAL GÜLER",
    "BELMA AKSU",
    "RAZİYE KAYA",
  ],
  "endustriyel-kalipcilik": [ // 52
    "MEHMET CAN ÖZÇELİK",
    "YALÇIN DENİZ KILİÇ",
    "MAHMUT YİLANLİ",
    "ÖZCAN BAYKALLAR",
    "EMİRHAN ALP",
    "ÖMER FARUK SARI",
    "OĞULCAN KARA",
    "ABDULLAH TÜLEK",
    "KEREM OLUR",
    "SAİM EFE KANTAŞLI",
    "ADİL KOCAKURT",
    "İBRAHİM ARDA BOLU",
    "SEMİH KEREKLİ",
    "YİĞİT KORKMAZ",
    "ALPER GÜRBÜZ",
    "RAMAZAN DÖNMEZ",
    "ARDA YETİŞEN",
    "SERTAÇ PAŞALAR",
    "ZEYNEP TUĞÇE AKKUŞ",
    "NURETTİN BARAN BAKAL",
    "UMUT KAZANIR",
    "İSMAİL AKÇILAR",
    "SERKAN DİNÇER",
    "HAKKI EMİR ULAS",
    "BATUHAN SEKİZLER",
    "SEZAİ VATAN",
    "FATİH ŞAHİN",
    "RAMAZAN BAYAT",
    "AHMET TAHA GÜLMEZ",
    "ALİ AKDAĞ",
    "EFE ŞAHİN",
    "SOYKAN DEMİREL",
    "HALİL MERT YAKAR",
    "MERYEM ZÜLAL TANRIKULU",
    "MERTCAN PAŞA",
    "YİĞİT ÇAĞAN ÇETİN",
    "CEMAL CEYHAN",
    "ENES CEYLAN",
    "BURAK YİĞİT KILIÇ",
    "TAHA YASİN ATAMAN",
    "UMUT ARTÜRK",
    "İBRAHİM ÇAYIR",
    "BERAT ÇIRAK",
    "EKREM DOĞRU",
    "NURTEN SONAY AVCI ASLAN",
    "EFE KARATEKİN",
    "ERTUĞRUL SAĞCAN",
    "MUHARREM AKYEL",
    "FİLİZ SAĞLAM",
    "SERPİL KOCADAYIOĞULLARI",
    "BEŞRİ EMRE",
    "MİRZA CAN BAĞIŞ",
  ],
  "imalat-yurutme-sistemleri-operatorlugu": [ // 29
    "AZRA HANÇERLİOĞULLARI",
    "CEREN CAŞKIR",
    "EMİRHAN DURAK",
    "EMİR ŞENSOYDAN",
    "MEHMET TALHA TEKOĞLU",
    "NADİR ÖLMEZ",
    "SUDE KELEŞ",
    "ZEHRA KANSU",
    "NECATİ DOĞRU",
    "EFE KAAN ÇAM",
    "YAĞIZ KEMAL TABAK",
    "KEREM MADALI",
    "BURAK KAÇAR",
    "İSMET DENİZ AZAK",
    "FURKAN YAVUZ",
    "SENİH KERETMİTÇİOĞLU",
    "MUSTAFA BUZKAN",
    "ARDA KAYNAK",
    "GÖKHAN ÇİFTÇİ",
    "ARDA SOLAK",
    "EFE KIZIK",
    "YİĞİT ŞENSES",
    "KEMAL SOYYILMAZ",
    "MEHMET BİNGÖL",
    "ALİCAN PAA",
    "ABDULLAH BUĞRA GÜN",
    "ŞEVVAL UĞUR",
    "BİLGE BEKTAŞ",
    "SEMA NUR TATLI",
  ],
  "mekatronik": [ // 50
    "ERTAN ÖDEN",
    "İSMAİL MEHMET KARAKOÇ",
    "KEREM ÖZYİĞİT",
    "EFE FURKAN ÖZİŞÇİ",
    "EFE CEMAL DİZ",
    "İSMAİL DEMİRTAŞ",
    "FATİH CEM OCAKOĞLU",
    "AYHAN SARAYKÖYLÜ",
    "KEMAL KARA",
    "RİYAD ULAŞ BEKFİLAVİOĞLU",
    "MEHMET ÇELİKCİ",
    "ERAY YİĞİT",
    "EREN YİĞİT",
    "MERT DALGIÇ",
    "ONUR TOPUZ",
    "EMİR MARANGOZ",
    "MUSTAFA FURKAN DOĞAN",
    "EKREM BERK USLU",
    "ONUR SALLAN",
    "KERİM BOZKURT",
    "İSMAİL KURULU",
    "SÜLEYMAN GİRGİN",
    "DENİZ KAÇAR",
    "İBRAHİM BERK İLDAY",
    "EMİRHAN SADIÇ",
    "MEHMET DEMİRTEKİN",
    "ENES KAAN IŞIK",
    "KADİR KARGA",
    "EMİRHAN GÜLTEKİN",
    "FERDUN EMİR ALBAĞLAR",
    "AHMET SAFA GENÇYILMAZ",
    "CEREN ÖZDEMİR",
    "FURKAN KAYLESİZ",
    "MİR ŞAHİN UÇAR",
    "İREM KIRCAN",
    "BURAK AÇIKGÖZ",
    "YUNUS EMRE TEKNE",
    "MEHMET KEREM KIZIL",
    "AYŞE ACAR",
    "MEHMET AŞUROĞLU",
    "YİĞİT ÖZYURT",
    "EMİR TAHA DOĞMUŞ",
    "MUHAMMET EREN GÜROL",
    "ARZU ŞAHİN ÜNAL",
    "HALİL AK",
    "FURKAN SAĞLAM",
    "DAVUT GÜLMEZ",
    "BEYZA BALCI",
    "HÜSEYİN EMRE PEHLİVAN",
    "ABDULLAH KAYA",
  ],
  "dijital-donusum-elektronigi": [ // 26
    "HALİS MEŞHUR",
    "ALPEREN KAYAN",
    "MEHMET SELİM BİLEN",
    "ABDULSAMET GÖK",
    "ELİFBEYZA GÜNER",
    "TOLGA KAAN AKGÜL",
    "ÖNDER ÇELİK",
    "ZEKİYENUR KORKMAZ",
    "BÜŞRA ÖZATAK",
    "BERAT DURAL",
    "MELİHA BOZKURT",
    "ARDA DALBAŞ",
    "AHMET EMİR MERİÇ",
    "AYŞENUR ERGÜN",
    "TUANA BOLLUK",
    "EGE KAYGISIZ",
    "SAMET İPEK",
    "OZAN GÜNDÜZ",
    "HAZAL SOYDAN",
    "ÇAĞLA AKÇEŞME",
    "ARDA YILMAZ BODUR",
    "DİLAN SEMİZ",
    "MERYEM AKBULUT",
    "MUHAMMET KÖROĞLU",
    "DİLARA BADEMCİOĞLU",
    "DENİZ PAKDURLAR",
  ],
  "elektrik": [ // 59
    "VAHİTCAN TEKİN",
    "MUSTAFA KAAN ÇALIŞKAN",
    "BERKE CAN TARLAK",
    "HÜSEYİN AYDAŞ",
    "BURAK SAL",
    "HÜSEYİN BALCI",
    "EYÜP CAN KILIÇ",
    "İSMAİL ÇETİN",
    "MUHSİN CAN",
    "MEHMET TAŞKAFA",
    "SELMAN ÇAMUR",
    "MEHMET ÇAĞRI",
    "REMZİ AMAÇ",
    "MELİH ÜNAL",
    "EREN KAVADARLI",
    "FURKAN DÖŞEME",
    "RECEP ARDA ŞAHİN",
    "YASİN GERMAN",
    "MEHMET KARAKAYA",
    "MUHAMMET ENSAR AKBULUT",
    "KORAY ALTIPARMAK",
    "YAKUB EMİRHAN AYDIN",
    "AHMET KARADUMAN",
    "BORA BATIN DEMİR",
    "MUHAMMED ALİ ÇETİN",
    "MUHAMMED SELİM BAYRAM",
    "GÖRKEM ERDEM",
    "FURKAN COŞKUN",
    "TALHA ÇINAR",
    "YAVUZ SAMET TINAZ",
    "YİĞİT KOÇ",
    "FURKAN SÖNMEZ",
    "RECEP SARIPINAR",
    "SEMİH TEZYOL",
    "MERT EGE ÖZCAN",
    "AHMET KOCAKAPLAN",
    "TUNÇ YUSUF ŞENGÜNOĞLU",
    "ŞEREF DURMAZ",
    "EREN GÖKTEN",
    "YİĞİT NEZİR KARADENİZ",
    "HÜSEYİN EFE",
    "YUNUS ÖZLÜK",
    "MUHAMMET EREN TORUN",
    "POLAT ÇINAR",
    "MAHMUT OZAN KARACA",
    "MUSTAFA OĞULCAN YILDIZ",
    "ÖMER FARUK BEYGİT",
    "EREN BALCI",
    "HALİME ONARAN",
    "AHMET TEN",
    "MERT KAYI",
    "MURAT İŞBAY",
    "NİLGÜN ŞEN",
    "MEHMET ENES YILDIZ",
    "EMİRHAN AYAZ",
    "HASAN MERT YEĞEN",
    "FURKAN DOĞANCIK",
    "ESAD AZMAN",
    "BERK ALİ TÜRKKAN",
  ],
  "alternatif-enerji-kaynaklari": [ // 51
    "ZEYNEP İBİŞ",
    "DİLARA TONAY",
    "SEMANUR SAMİ",
    "ENİSE SUDE DEĞİRMENCİ",
    "SEMANUR ÇAKMAK",
    "ESLEM SU GÖNÜLTAŞ",
    "BERİL ERCEYLAN",
    "BUSE CANBAZ",
    "AFRA İREM BALIK",
    "SILA DİNÇER",
    "BÜŞRA KOCAMAN",
    "MERVENUR TERZİOĞLU",
    "MERVE SENA ASLAN",
    "YAĞMUR CENGİZ",
    "SÜMEYRA SAĞLAM",
    "MEHRU ŞEVVAL ÜNAL",
    "RABİA ÖNDER",
    "MERVE NUR ONAR",
    "ÖZLEM AVCI",
    "SUDE NUR ÖZDEMİR",
    "EZGİ BUDAK",
    "RÜMEYSA BAYKALLAR",
    "İLAYDA OTAÇ",
    "NİSA FİRDEVS ÇİLGİNOĞLU",
    "TUĞÇE AKPINAR",
    "BURAK BALÇIK",
    "YİĞİT PAYKOÇ",
    "BERAN DEMİRKALE",
    "YAĞIZ EREN",
    "VOLKAN ASLANOĞLU",
    "EREN KOÇYİĞİT",
    "FURKAN EFE ATAY",
    "ARDA KARANFİL",
    "İHSAN EMRE ASLAN",
    "YİĞİT DOĞANTEKİN",
    "ÖMER ATILGAN",
    "EFE BAYKAN",
    "ÜNAL ERDELİKANLI",
    "AHMET GÜRLER",
    "MERT CAN KORKMAZ",
    "YAVUZ BAHADIR AKSOY",
    "ARDA DEMİRCİ",
    "GÖRKEM TURAN",
    "HAKTAN ERDALGIÇ",
    "ALİ EREN TANER",
    "RIDVAN KÜTAHYALI",
    "YUSUF ASLAN",
    "GÖKHAN SUNGUR",
    "MEHMET MERT DÖNMEZ",
    "HALİL BAYTEKİN",
    "İSMAİL HAKKI KARAKAYA",
  ],
  "bilgisayar-programciligi": [ // 55
    "ÖZDEMİR AKBULUT",
    "MEHMET KIVRAK",
    "OSMAN ORHAN AŞKIN",
    "ALP YANKI ULU",
    "RECEP SEFA BURGU",
    "İLHAN EGEMEN DURMUŞ",
    "ECENUR GEDİZ",
    "MUSTAFA İNAN",
    "ŞEYMA ZORLUOĞLU",
    "BURAK AŞIR",
    "KEREM IŞIK",
    "DENİZ GÜLMEZ",
    "EMİR GÜRBÜZ",
    "SELİN KURTEŞ",
    "AHMET AKSOY",
    "ELİF BOZKURT",
    "ARDA ENGİN",
    "EREN ALGÜL",
    "MUHAMMED MUSTAFA SERGİN",
    "DURUKAN İÇTEN",
    "İSMAİL ALPEREN TÜRKÖZ",
    "BARIŞ GÜLER",
    "BERK VARDAR",
    "ULAŞ ARDA KÖYLÜ",
    "MİRAÇ AYKUT KARMİL",
    "MELEK GÖKÇE",
    "YASİN ARDA",
    "SALİH GÜRLER",
    "ÖMER FARUK ERTAM",
    "NAZİF ENES ARICI",
    "EGE YAYLICIOĞLU",
    "İLKER KAYIR",
    "GÖKAY TUNALI",
    "DEMİRHAN KAYA",
    "SÜMEYYE ÇAYIR",
    "MİRZA EMEÇ",
    "BELİZ BAŞER",
    "EMİR NAİL AKŞİT",
    "NURULLAH YILDIRIM",
    "ARDA BULUNMAZ",
    "SEVGİ ÜNAL",
    "ÜMİT SELAHATTİN MOMOÇOĞLU",
    "YUSUF TALHA UYGUN",
    "SUNGUR ATEŞ",
    "SAMET BOL",
    "MEHMET KOÇ",
    "MELEK BAYRAM",
    "FATMA MERGEN",
    "MUHAMMET EMİN DOĞAN",
    "BEHİYE ÇELİK",
    "CANAN KESKİN",
    "CAN BERKANT POLAT",
    "OSMAN REHA BEZ",
    "EMİRHAN AYAZ",
    "MEHMET AVŞAR",
  ],
};
